services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      - BAKER_URL=http://baker:3000
      - MEDIAMTX_API=http://mediamtx:9997
    volumes:
      - pb_data:/pb_data
      - ./pocketbase/pb_public:/pb_public
      - ./pocketbase/pb_hooks:/pb_hooks
      - ./pocketbase/pb_migrations:/pb_migrations
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mediamtx:
    image: bluenviron/mediamtx:1.11.2
    restart: unless-stopped
    ports:
      - "9997:9997" # API
      - "8554:8554" # RTSP
      - "8888:8888" # API and metrics
      - "8889:8889" # HLS
      - "1935:1935" # RTMP
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    image: ghcr.io/skylineagle/switcher/app:main
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - pocketbase
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  baker:
    image: ghcr.io/skylineagle/switcher/baker:main
    build:
      context: .
      dockerfile: Dockerfile.baker
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MEDIAMTX_API=http://mediamtx:9997
      - POCKETBASE_URL=http://pocketbase:8090
      - SWITCHER_API_URL=http://switcher:8000
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  switcher:
    image: ghcr.io/skylineagle/switcher/switcher:main
    build:
      context: .
      dockerfile: Dockerfile.switcher
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MEDIAMTX_API=http://mediamtx:9997
      - POCKETBASE_URL=http://pocketbase:8090
    depends_on:
      - pocketbase
      - mediamtx
      - baker
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge

volumes:
  pb_data:
