export const cameraConfigSchema = {
  type: "object",
  properties: {
    name: { type: "string" },
    source: { type: "string" },
    sourceFingerprint: { type: "string" },
    sourceOnDemand: { type: "boolean" },
    sourceOnDemandStartTimeout: { type: "string" },
    sourceOnDemandCloseAfter: { type: "string" },
    maxReaders: { type: "number" },
    srtReadPassphrase: { type: "string" },
    fallback: { type: "string" },
    record: { type: "boolean" },
    recordPath: { type: "string" },
    recordFormat: { type: "string" },
    recordPartDuration: { type: "string" },
    recordSegmentDuration: { type: "string" },
    recordDeleteAfter: { type: "string" },
    overridePublisher: { type: "boolean" },
    srtPublishPassphrase: { type: "string" },
    rtspTransport: { type: "string" },
    rtspAnyPort: { type: "boolean" },
    rtspRangeType: { type: "string" },
    rtspRangeStart: { type: "string" },
    sourceRedirect: { type: "string" },
    rpiCameraCamID: { type: "number" },
    rpiCameraWidth: { type: "number" },
    rpiCameraHeight: { type: "number" },
    rpiCameraHFlip: { type: "boolean" },
    rpiCameraVFlip: { type: "boolean" },
    rpiCameraBrightness: { type: "number" },
    rpiCameraContrast: { type: "number" },
    rpiCameraSaturation: { type: "number" },
    rpiCameraSharpness: { type: "number" },
    rpiCameraExposure: { type: "string" },
    rpiCameraAWB: { type: "string" },
    rpiCameraAWBGains: {
      type: "array",
      items: { type: "number" },
      minItems: 2,
      maxItems: 2,
    },
    rpiCameraDenoise: { type: "string" },
    rpiCameraShutter: { type: "number" },
    rpiCameraMetering: { type: "string" },
    rpiCameraGain: { type: "number" },
    rpiCameraEV: { type: "number" },
    rpiCameraROI: { type: "string" },
    rpiCameraHDR: { type: "boolean" },
    rpiCameraTuningFile: { type: "string" },
    rpiCameraMode: { type: "string" },
    rpiCameraFPS: { type: "number" },
    rpiCameraAfMode: { type: "string" },
    rpiCameraAfRange: { type: "string" },
    rpiCameraAfSpeed: { type: "string" },
    rpiCameraLensPosition: { type: "number" },
    rpiCameraAfWindow: { type: "string" },
    rpiCameraFlickerPeriod: { type: "number" },
    rpiCameraTextOverlayEnable: { type: "boolean" },
    rpiCameraTextOverlay: { type: "string" },
    rpiCameraCodec: { type: "string" },
    rpiCameraIDRPeriod: { type: "number" },
    rpiCameraBitrate: { type: "number" },
    rpiCameraProfile: { type: "string" },
    rpiCameraLevel: { type: "string" },
    runOnInit: { type: "string" },
    runOnInitRestart: { type: "boolean" },
    runOnDemand: { type: "string" },
    runOnDemandRestart: { type: "boolean" },
    runOnDemandStartTimeout: { type: "string" },
    runOnDemandCloseAfter: { type: "string" },
    runOnUnDemand: { type: "string" },
    runOnReady: { type: "string" },
    runOnReadyRestart: { type: "boolean" },
    runOnNotReady: { type: "string" },
    runOnRead: { type: "string" },
    runOnReadRestart: { type: "boolean" },
    runOnUnread: { type: "string" },
    runOnRecordSegmentCreate: { type: "string" },
    runOnRecordSegmentComplete: { type: "string" },
  },
  required: ["name", "source"],
} as const;
